// <auto-generated />
using System;
using ECommerceServices.Api.ShoppingCart.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ECommerceServices.Api.ShoppingCart.Migrations
{
    [DbContext(typeof(SessionContext))]
    partial class SessionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ECommerceServices.Api.ShoppingCart.Model.SessionDetail", b =>
                {
                    b.Property<int>("SessionDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("ProductSelected")
                        .HasColumnType("text");

                    b.Property<int>("SessionHeader")
                        .HasColumnType("int");

                    b.Property<int>("SessionHeaderId")
                        .HasColumnType("int");

                    b.HasKey("SessionDetailId");

                    b.HasIndex("SessionHeaderId");

                    b.ToTable("SessionDetail");
                });

            modelBuilder.Entity("ECommerceServices.Api.ShoppingCart.Model.SessionHeader", b =>
                {
                    b.Property<int>("SessionHeaderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime");

                    b.HasKey("SessionHeaderId");

                    b.ToTable("SessionHeader");
                });

            modelBuilder.Entity("ECommerceServices.Api.ShoppingCart.Model.SessionDetail", b =>
                {
                    b.HasOne("ECommerceServices.Api.ShoppingCart.Model.SessionHeader", null)
                        .WithMany("SessionDetails")
                        .HasForeignKey("SessionHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
